import express from 'express';
import passport from 'passport';
import session from 'express-session';
import cookieParser from 'cookie-parser';
import cors from 'cors';
import { configurePassport } from './passportConfig';

const app = express();

// Middleware
app.use(cors({ origin: true, credentials: true }));
app.use(express.json());
app.use(cookieParser());
app.use(session({
    secret: 'richard-automotive-secret', // Use env in production
    resave: false,
    saveUninitialized: false,
    cookie: { secure: process.env.NODE_ENV === 'production' }
}));

// Initialize Passport
configurePassport();
app.use(passport.initialize());
app.use(passport.session());

// Routes
app.post('/login', (req, res, next) => {
    passport.authenticate('local', (err: any, user: any, info: any) => {
        if (err) {
            res.status(500).json(err);
            return;
        }
        if (!user) {
            res.status(401).json(info);
            return;
        }

        req.logIn(user, (err) => {
            if (err) {
                res.status(500).json(err);
                return;
            }
            res.json({ message: 'Logged in successfully', user });
        });
    })(req, res, next);
});

app.get('/profile', (req, res) => {
    if (req.isAuthenticated()) {
        res.json(req.user);
    } else {
        res.status(401).json({ message: 'Not authenticated' });
    }
});

app.get('/logout', (req, res, next) => {
    req.logout((err) => {
        if (err) return next(err);
        res.json({ message: 'Logged out' });
    });
});

app.get('/php-bridge', (req, res) => {
    // Simulate PHP Headers
    res.setHeader('X-Powered-By', 'PHP/8.2.12');
    res.setHeader('Content-Type', 'application/json; charset=UTF-8');

    const timestamp = Math.floor(Date.now() / 1000);
    const mockValue = Math.floor(Math.random() * 100) + 1;

    // Simulate classic PHP response structure
    res.json({
        status: "success",
        data: {
            php_runtime: "Zend Engine v4.2.12",
            timestamp: timestamp,
            execution_time_ms: 4.2,
            memory_usage: "2.4MB",
            result_value: mockValue,
            message: "Response generated by legacy PHP/CGI simulator"
        },
        _debug: {
            script_path: "/var/www/html/api/bridge.php",
            server_software: "Apache/2.4.58 (Unix) OpenSSL/3.0.12"
        }
    });
});

export default app;
