export const MARGIN_RULES = {
    HIGH_PROBABILITY_THRESHOLD: 90,
    MEDIUM_PROBABILITY_THRESHOLD: 80,
    OLD_STOCK_DAYS: 30,
    RECENT_STOCK_DAYS: 15,
    DISCOUNT_RATES: {
        AGGRESSIVE: 0.05, // 5%
        STANDART: 0.03,   // 3%
        NONE: 0
    }
};
