export interface CityInfo {
  name: string;
  slug: string;
  meta: string;
  region: string;
  zipCodes: string[];
  landmarks: string[];
  population: string;
}

export const CITIES_PR: Record<string, CityInfo> = {
  bayamon: {
    name: 'Bayamón',
    slug: 'bayamon',
    meta: 'el Dealer #1 de Bayamón',
    region: 'Zona Metro',
    zipCodes: ['00956', '00957', '00959', '00960', '00961'],
    landmarks: ['Rexville', 'Santa Rosa Mall', 'Lomas Verdes'],
    population: '185,996',
  },
  'san-juan': {
    name: 'San Juan',
    slug: 'san-juan',
    meta: 'exclusividad en la Capital',
    region: 'Capital',
    zipCodes: [
      '00901',
      '00907',
      '00909',
      '00911',
      '00913',
      '00917',
      '00918',
      '00920',
      '00921',
      '00923',
      '00924',
      '00925',
      '00926',
      '00927',
      '00934',
      '00936',
    ],
    landmarks: ['Condado', 'Hato Rey', 'Isla Verde', 'Santurce', 'Miramar'],
    population: '342,259',
  },
  guaynabo: {
    name: 'Guaynabo',
    slug: 'guaynabo',
    meta: 'unidades de lujo en Guaynabo City',
    region: 'Zona Metro',
    zipCodes: ['00965', '00966', '00968', '00969', '00970', '00971'],
    landmarks: ['Garden Hills', 'Caparra', 'Downtown Center'],
    population: '89,780',
  },
  ponce: {
    name: 'Ponce',
    slug: 'ponce',
    meta: 'la Perla del Sur con Richard Automotive',
    region: 'Sur',
    zipCodes: ['00716', '00717', '00728', '00730', '00731', '00732', '00733', '00734'],
    landmarks: ['Plaza Las Américas Ponce', 'Museo de Arte', 'La Guancha'],
    population: '132,502',
  },
  caguas: {
    name: 'Caguas',
    slug: 'caguas',
    meta: 'financiamiento expreso en el Turabo',
    region: 'Centro-Este',
    zipCodes: ['00725', '00726', '00727'],
    landmarks: ['Las Catalinas Mall', 'Jardín Botánico', 'Centro Criollo'],
    population: '127,244',
  },
  carolina: {
    name: 'Carolina',
    slug: 'carolina',
    meta: 'la Ciudad de los Campeones confía en Richard',
    region: 'Zona Metro',
    zipCodes: ['00979', '00982', '00983', '00984', '00985', '00987'],
    landmarks: ['Plaza Carolina', 'Isla Verde', 'Roberto Clemente Coliseum'],
    population: '147,372',
  },
  mayaguez: {
    name: 'Mayagüez',
    slug: 'mayaguez',
    meta: 'el mejor inventario del Oeste',
    region: 'Oeste',
    zipCodes: ['00680', '00681', '00682'],
    landmarks: ['Plaza del Caribe', 'RUM', 'Zoológico de Mayagüez'],
    population: '71,083',
  },
  arecibo: {
    name: 'Arecibo',
    slug: 'arecibo',
    meta: 'financiamiento garantizado en La Villa del Capitán Correa',
    region: 'Norte',
    zipCodes: ['00612', '00613', '00614'],
    landmarks: ['Cueva del Indio', 'Faro de Arecibo', 'Plaza del Atlántico'],
    population: '87,242',
  },
  'toa-baja': {
    name: 'Toa Baja',
    slug: 'toa-baja',
    meta: 'tu dealer de confianza en Levittown',
    region: 'Zona Metro',
    zipCodes: ['00949', '00950', '00951', '00952'],
    landmarks: ['Levittown', 'Punta Salinas'],
    population: '75,204',
  },
  humacao: {
    name: 'Humacao',
    slug: 'humacao',
    meta: 'autos certificados para el Este de PR',
    region: 'Este',
    zipCodes: ['00791', '00792'],
    landmarks: ['Palmas del Mar', 'Plaza Humacao'],
    population: '44,328',
  },
  'vega-alta': {
    name: 'Vega Alta',
    slug: 'vega-alta',
    meta: 'financiamiento directo desde Central Ford',
    region: 'Norte',
    zipCodes: ['00692'],
    landmarks: ['Central Ford', 'Cerro Gordo Beach'],
    population: '39,951',
  },
  dorado: {
    name: 'Dorado',
    slug: 'dorado',
    meta: 'unidades Premium y de lujo en el Paraíso Dorado',
    region: 'Norte',
    zipCodes: ['00646'],
    landmarks: ['Dorado Beach Resort', 'Sabanera Dorado', 'Gran Caribe Mall'],
    population: '35,891',
  },
  'vega-baja': {
    name: 'Vega Baja',
    slug: 'vega-baja',
    meta: 'financiamiento expreso en el Melao Melao',
    region: 'Norte',
    zipCodes: ['00693', '00694'],
    landmarks: ['Puerto Nuevo Beach', 'Plaza Las Flores', 'Teatro Fénix'],
    population: '54,414',
  },
  manati: {
    name: 'Manatí',
    slug: 'manati',
    meta: 'tu dealer de confianza en la Atenas de Puerto Rico',
    region: 'Norte',
    zipCodes: ['00674'],
    landmarks: ['Plaza Atenas', 'Trigo Golden Plaza', 'Casino de Manatí'],
    population: '39,492',
  },
  hatillo: {
    name: 'Hatillo',
    slug: 'hatillo',
    meta: 'los mejores negocios en la Capital de la Industria Lechera',
    region: 'Norte',
    zipCodes: ['00659'],
    landmarks: ['Plaza del Norte', 'Paseo del Carmen', 'Playa Sardinera'],
    population: '38,486',
  },
  isabela: {
    name: 'Isabela',
    slug: 'isabela',
    meta: 'unidades de calidad en el Jardín del Noroeste',
    region: 'Noroeste',
    zipCodes: ['00662'],
    landmarks: ['Jobos Beach', 'Guajataca Tunnel', 'Plaza Isabela'],
    population: '42,943',
  },
  'cabo-rojo': {
    name: 'Cabo Rojo',
    slug: 'cabo-rojo',
    meta: 'el chinchorreo y financiamiento del Suroeste',
    region: 'Suroeste',
    zipCodes: ['00623'],
    landmarks: ['Combate Beach', 'Boquerón', 'Punta Higuero Lighthouse'],
    population: '47,515',
  },
  aguadilla: {
    name: 'Aguadilla',
    slug: 'aguadilla',
    meta: 'el dealer de autos líder en la Villa del Ojo de Agua',
    region: 'Oeste',
    zipCodes: ['00603', '00604', '00605'],
    landmarks: ['Crash Boat Beach', 'Aguadilla Mall', 'Ramey Base'],
    population: '50,265',
  },
  fajardo: {
    name: 'Fajardo',
    slug: 'fajardo',
    meta: 'autos certificados en el Hub del Este de PR',
    region: 'Este',
    zipCodes: ['00738'],
    landmarks: ['Las Croabas', 'Fajardo Bioluminescent Bay', 'Marina Puerto Chico'],
    population: '32,189',
  },
  'trujillo-alto': {
    name: 'Trujillo Alto',
    slug: 'trujillo-alto',
    meta: 'financiamiento aprobado en la Ciudad del Recueste',
    region: 'Zona Metro',
    zipCodes: ['00976'],
    landmarks: ['Carraízo Dam', 'Paseo del Bicentenario', 'Plaza Trujillo'],
    population: '67,748',
  },
  guayama: {
    name: 'Guayama',
    slug: 'guayama',
    meta: 'tu dealer líder en la Ciudad Bruja',
    region: 'Sur',
    zipCodes: ['00784', '00785'],
    landmarks: ['Plaza de Guayama', 'Paseo del Poeta', 'Pozuelo Beach'],
    population: '36,614',
  },
};
