export type { Lead, BehavioralFingerprint, PredictiveInsight, OutreachOpportunity, MarginAdjustment } from '@/shared/types/lead';
export type { LeadRepository } from './api/LeadRepository';
export type { PredictiveRepository } from './api/PredictiveRepository';
export { SupabaseLeadRepository } from './api/repositories/SupabaseLeadRepository';
export { SupabasePredictiveRepository } from './api/repositories/SupabasePredictiveRepository';
export { SupabaseSubscriberRepository, SupabaseSurveyRepository } from './api/repositories/SupabaseCaptureRepository';
export type { ScoringResult } from './api/leadScoringService';
export { calculateLeadScore, sortLeadsByPriority } from './api/leadScoringService';
export { leadService } from './api/leadService';
export { LeadMapper } from './lib/mappers/LeadMapper';
