name: DevSecOps Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-scans:
    name: Gitleaks & Grype Security Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Grype Vulnerability Scan
        uses: anchore/scan-action@3343887d815d7b07465f6fdcd395bd66508d486a # v3
        with:
          path: "."
          fail-build: false
          severity-cutoff: high
