import { Car } from '@/entities/inventory';

export const initialInventoryData: Omit<Car, 'id'>[] = [
  {
    name: 'Hyundai Tucson 2026',
    make: 'Hyundai',
    model: 'Tucson',
    year: 2026,
    vin: 'HT2026XJ910239',
    color: 'Titanium Gray',
    price: 39500,
    mileage: 0,
    type: 'suv',
    badge: 'Rediseñado',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?q=80&w=1200&auto=format&fit=crop',
    status: 'available',
    featured: true,
  },
  {
    name: 'Hyundai Elantra 2026',
    make: 'Hyundai',
    model: 'Elantra',
    year: 2026,
    vin: 'HE2026EL881023',
    color: 'Phantom Black',
    price: 28900,
    mileage: 0,
    type: 'sedan',
    badge: 'Deportivo',
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?q=80&w=1200&auto=format&fit=crop',
    status: 'available',
    featured: true,
  },
  {
    name: 'Hyundai Venue 2026',
    make: 'Hyundai',
    model: 'Venue',
    year: 2026,
    vin: 'HV2026VN771044',
    color: 'Snow White Pearl',
    price: 24500,
    mileage: 0,
    type: 'suv',
    badge: 'Compacto',
    image: 'https://images.unsplash.com/photo-1672820415487-c534a8ee22ff?q=80&w=1200&auto=format&fit=crop',
    status: 'available',
    featured: false,
  },
  {
    name: 'Hyundai Santa Fe 2026',
    make: 'Hyundai',
    model: 'Santa Fe',
    year: 2026,
    vin: 'HS2026SF661055',
    color: 'Earthly Bronze',
    price: 44200,
    mileage: 0,
    type: 'suv',
    badge: 'Más Espacio',
    image: 'https://images.unsplash.com/photo-1646728502468-06d9c7b3c2c2?q=80&w=1200&auto=format&fit=crop',
    status: 'available',
    featured: true,
  },
  {
    name: 'Hyundai Palisade 2026',
    make: 'Hyundai',
    model: 'Palisade',
    year: 2026,
    vin: 'HP2026PL551066',
    color: 'Midnight Blue',
    price: 58900,
    mileage: 0,
    type: 'luxury',
    badge: 'Flagship',
    image: 'https://images.unsplash.com/photo-1621112904887-419379ce6824?q=80&w=1200&auto=format&fit=crop',
    status: 'available',
    featured: true,
  },
  {
    name: 'Hyundai Kona 2026',
    make: 'Hyundai',
    model: 'Kona',
    year: 2026,
    vin: 'HK2026KO441077',
    color: 'Cyber Sage',
    price: 34500,
    mileage: 0,
    type: 'suv',
    badge: 'Electrizante',
    image: 'https://images.unsplash.com/photo-1672278374378-8ef184d2e685?q=80&w=1200&auto=format&fit=crop',
    status: 'available',
    featured: false,
  },
  {
    name: "2026 Ford Mustang GT California Special",
    make: "Ford",
    model: "Mustang GT",
    year: 2026,
    vin: "1FA6P8CFXG5" + Math.random().toString(36).substring(2, 7).toUpperCase(),
    color: "Shadow Black",
    price: 76995,
    mileage: 0,
    type: "luxury",
    badge: "In Stock",
    image: "/inventory/ford/mustang-gt-cs.png",
    status: "available",
    featured: true,
  },
  {
    name: "2026 Ford F-150 Raptor R",
    make: "Ford",
    model: "F-150 Raptor",
    year: 2026,
    vin: "1FTFW4L9XRF" + Math.random().toString(36).substring(2, 7).toUpperCase(),
    color: "Carbonized Gray Metallic",
    price: 159995,
    mileage: 5,
    type: "pickup",
    badge: "High Performance",
    image: "/inventory/ford/f150-raptor-r.png",
    status: "available",
    featured: true,
  },
  {
    name: "2025 Ford Ranger STX Canopy Edition",
    make: "Ford",
    model: "Ranger",
    year: 2025,
    vin: "1FTER4EHXPF" + Math.random().toString(36).substring(2, 7).toUpperCase(),
    color: "Oxford White",
    price: 49995,
    mileage: 10,
    type: "pickup",
    badge: "Ready for Work",
    image: "/inventory/ford/ranger-stx-canopy.png",
    status: "available",
    featured: false,
  },
  {
    name: "2026 Ford Explorer Active",
    make: "Ford",
    model: "Explorer",
    year: 2026,
    vin: "1FM5K7DH5GA" + Math.random().toString(36).substring(2, 10).toUpperCase(),
    color: "Vapor Blue Metallic",
    price: 52995,
    mileage: 0,
    type: "suv",
    badge: "New Arrival",
    image: "/inventory/ford/explorer-active.png",
    status: "available",
    featured: true,
  },
  {
    name: "2026 Ford Bronco 4-Door Base",
    make: "Ford",
    model: "Bronco",
    year: 2026,
    vin: "1FMEE5DP6RF" + Math.random().toString(36).substring(2, 7).toUpperCase(),
    color: "Cactus Gray",
    price: 64995,
    mileage: 0,
    type: "suv",
    badge: "Adventure Ready",
    image: "/inventory/ford/bronco-base.png",
    status: "available",
    featured: false,
  },
  {
    name: "2025 Ford Bronco Sport BigBend",
    make: "Ford",
    model: "Bronco Sport",
    year: 2025,
    vin: "3FTTW8F96RR" + Math.random().toString(36).substring(2, 7).toUpperCase(),
    color: "Hot Pepper Red Metallic",
    price: 41995,
    mileage: 0,
    type: "suv",
    badge: "Special Offer",
    image: "/inventory/ford/bronco-sport-bb.png",
    status: "available",
    featured: false,
  },
];
